export const ADD_NEW_TODO = "ADD_NEW_TODO";
export const GET_ALL_TODOS = "GET_ALL_TODOS";
export const UPDATE_TODO = "TOGGLE_TODO_COMPLETED";
export const DELETE_TODO = "TOGGLE_TODO_COMPLETED";
export const TOGGLE_TODO_COMPLETED = "TOGGLE_TODO_COMPLETED";